workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 80
    environment:
      groups:
        - unity_ios  # <--- (Includes XCODE_PROJECT, XCODE_SCHEME)
        - unity # <-- (Includes UNITY_HOME, UNITY_SERIAL, UNITY_USERNAME and UNITY_PASSWORD, UNITY_VERSION, UNITY_VERSION_CHANGESET, CM_CLONE_DEPTH, UNITY_IOS_DIR, UNITY_MAC_DIR )
        - appstore_credentials # <-- (Includes APP_STORE_APP_ID, BUNDLE_ID, APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY )   
      vars:
        BUILD_SCRIPT: BuildIos
      cocoapods: default
    scripts:
      - &set_up_keychain
        name: Set up keychain
        script: |
          keychain initialize
      - &install_unity_ios
        name: Install Unity version
        script: |
          /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless install --version $UNITY_VERSION --changeset $UNITY_VERSION_CHANGESET
          /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless install-modules --version $UNITY_VERSION -m ios
        ignore_failure: true
      - &activate_unity_license
        name: Activate Unity License
        script: |
          /Applications/Unity/Hub/Editor/${UNITY_VERSION}/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_EMAIL?} -password ${UNITY_PASSWORD?}
      - &fetch_signing_files
        name: Fetch signing files
        script: |
          # You can allow creating resources if existing are not found with `--create` flag
          app-store-connect fetch-signing-files "com.ranchcode.bloodontheclocktower" \
          --type IOS_APP_STORE \
          --create
      - &add_certificates
        name: Use system default keychain
        script: |
          keychain add-certificates
      - &setup_code_signing
        name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - &build_xcode_project
        name: Build the Xcode project
        script: |
          /Applications/Unity/Hub/Editor/${UNITY_VERSION}/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -projectPath ./BloodOnTheClocktower -executeMethod BuildScript.$BUILD_SCRIPT -nographics -buildTarget iOS
      - &build_ipa
        name: Build ipa for distribution
        script: |
          xcode-project build-ipa --project "BloodOnTheClocktower/$UNITY_IOS_DIR/$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    cache:
      cache_paths:
        - /Applications/Unity/Hub/Editor/${UNITY_VERSION}
        - $CM_BUILD_DIR/BloodOnTheClocktower/Library
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing: 
      scripts:
        - &deactivate_unity_license
          name: Deactivate Unity License
          script: /Applications/Unity\ Hub.app/Contents/Frameworks/UnityLicensingClient_V1.app/Contents/MacOS/Unity.Licensing.Client --return-ulf --username ${UNITY_EMAIL?} --password ${UNITY_PASSWORD?}
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
  ########################################################################################
  unity-ios-adhoc-workflow:
    name: Unity iOS Ad-Hoc workflow
    instance_type: mac_mini_m1
    max_build_duration: 80
    environment:
      groups:
        - unity_ios 
        - unity 
        - appstore_credentials 
      vars:
        BUILD_SCRIPT: BuildIos
      ios_signing: 
        distribution_type: ad_hoc
        bundle_identifier: com.ranchcode.bloodontheclocktower
      cocoapods: default
    scripts:
      - *install_unity_ios
      - *activate_unity_license
      - *build_xcode_project
      - *setup_code_signing
      - *build_ipa
    cache:
      cache_paths:
        - /Applications/Unity/Hub/Editor/${UNITY_VERSION}
        - $CM_BUILD_DIR/BloodOnTheClocktower/Library
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      scripts:
        - *deactivate_unity_license
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
