export default [
  { id: "grandmother" },
  { id: "sailor" },
  { id: "chambermaid" },
  { id: "exorcist" },
  { id: "innkeeper" },
  { id: "gambler" },
  { id: "gossip" },
  { id: "courtier" },
  { id: "professor" },
  { id: "minstrel" },
  { id: "tea_lady" },
  { id: "pacifist" },
  { id: "fool" },
  { id: "tinker" },
  { id: "moonchild" },
  { id: "goon" },
  { id: "lunatic" },
  { id: "godfather" },
  { id: "devils_advocate" },
  { id: "assassin" },
  { id: "mastermind" },
  { id: "zombuul" },
  { id: "pukka" },
  { id: "shabaloth" },
  { id: "po" },
] as const;
