export default [
  { id: "washerwoman" },
  { id: "librarian" },
  { id: "investigator" },
  { id: "chef" },
  { id: "empath" },
  { id: "fortune_teller" },
  { id: "undertaker" },
  { id: "monk" },
  { id: "ravenkeeper" },
  { id: "virgin" },
  { id: "slayer" },
  { id: "soldier" },
  { id: "mayor" },
  { id: "butler" },
  { id: "drunk" },
  { id: "recluse" },
  { id: "saint" },
  { id: "poisoner" },
  { id: "spy" },
  { id: "scarlet_woman" },
  { id: "baron" },
  { id: "imp" },
] as const;
