#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
set -euo

# Run 'npm run format:check'
# If it fails, run 'npm run format' and then fail
# If it succeeds, then also run 'npm run typecheck'
# If that fails, fail

npm run format:check || (npm run format && exit 1)
npm run typecheck || exit 1
